### ISSUE TITLE
View Organizations/Societies Grid - The Image uploaded is not completely displayed on the grip

### ISSUE THREAD

**Issue by pratsajency** [ajency/EUC#127]
The logo/images uploaded are not displayed completely on the grid.
Tried uploading image size of 600x250px.

Actual Image - http://euc.uk.com/wp-content/uploads/2014/12/St-Marys-University-Twickenham-1.jpg
View on - http://euc.uk.com/universities/

![21](https://cloud.githubusercontent.com/assets/3326712/5592521/68140558-91f9-11e4-9d6a-1ffe0a518395.png)

**Comment by jeromie** [comment]
Done. Media settings changed in the dashboard. @pratsajency 

Note: Better to upload vertical or square images instead of horizontal as the images always occupies 100% width of the container and on some screen sizes, horizontal images may not cover the entire height of the container and leave gray strips above and below the image.
